// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB68UuO8nOCI6R46hbPnHZDBkJs48djppo',
    appId: '1:493556179206:web:b39b92c9315d856e563e87',
    messagingSenderId: '493556179206',
    projectId: 'fassion-valley',
    authDomain: 'fassion-valley.firebaseapp.com',
    storageBucket: 'fassion-valley.appspot.com',
    measurementId: 'G-PPVJMJLX59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwvyyDIwMQWOTPD_0Gwpeme_Z-BexPx3Q',
    appId: '1:493556179206:android:a0ab69c732e6fe71563e87',
    messagingSenderId: '493556179206',
    projectId: 'fassion-valley',
    storageBucket: 'fassion-valley.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhyR1QGJmGcyPbjjFQZDyk65qAJPFnH5o',
    appId: '1:493556179206:ios:350b9a7c400cc35a563e87',
    messagingSenderId: '493556179206',
    projectId: 'fassion-valley',
    storageBucket: 'fassion-valley.appspot.com',
    iosClientId:
        '493556179206-0sb0lbeenptm1bmknev84anp1hhpkg8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionValley',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhyR1QGJmGcyPbjjFQZDyk65qAJPFnH5o',
    appId: '1:493556179206:ios:350b9a7c400cc35a563e87',
    messagingSenderId: '493556179206',
    projectId: 'fassion-valley',
    storageBucket: 'fassion-valley.appspot.com',
    iosClientId:
        '493556179206-0sb0lbeenptm1bmknev84anp1hhpkg8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionValley',
  );
}
